// First names array
const firstNames = ["Abad", "Abdennasser", "Amghar", "Abbas", "Abdelmoula", "Amimar", "Abbou", "Allal", "Amine", "Abdelaalim", "Abdennour", "Amjad", "Abdelaati", "Abderaouf", "Ammar", "Abdeladim", "Abderrafie", "Amrane", "Abdelali", "Abderrazak", "Anis", "Abdelaziz", "Abdessabour", "Anouar", "Abdelbadie", "Abdessadek", "Antar", "Abdelbaki", "Abdessafi", "Antara", "Abdelbasset", "Abdessalam", "Aouab", "Abdelfattah", "Abdessamad", "Aouiss", "Abdelghafour", "Abdessamie", "Arbi", "Abdelghani", "Abdessatar", "Archane", "Abdelhadi", "Abdou", "Aref", "Abdelhafid", "Abdourabih", "Arif", "Abdelhak", "Abdrabbou", "Arij", "Abdelhakim", "Abed", "Arkam", "Abdelhalim", "Abid", "Arsalane", "Abdelhamid", "Aboubaki", "Assad", "Abdelhaq", "Aboubakr", "Assil", "Abdelilah", "Aboud", "Assou", "Abdeljabbar", "Achour", "Atef", "Abdeljalil", "Achraf", "Atf", "Abdeljaouad", "Adam", "Atik", "Abdelkabir", "Addi", "Atiq", "Abdelkader", "Adel", "Atouf", "Abdelkamel", "Adham", "Ayache", "Abdelkarim", "Adib", "Ayachi", "Abdelkhalek", "Adil", "Ayad", "Abdelkouddous", "Adnane", "Ayich", "Abdellah", "Afif", "Ayman", "Abdellatif", "Ahmed", "Ayoub", "Abdelmalek", "Aissa", "Azam", "Abdelmoghit", "Akram", "Azhar", "Abdelmonaim", "Alaeeddine", "Azmi", "Abdelmouaiz", "Alami", "Azzam", "Abdelmoughit", "Ali", "Azzeddine", "Abdelmouhaimin", "Aliane", "Azzelarab", "Abdelmoujib", "Alif", "Azzouz", "Abdelmoumen", "Alilou", "Abdelmouttalib", "Allali", "Abdelouadoud", "Allou", "Abdelouafi", "Allouch", "Abdelouahab", "Amar", "Abdelouahid", "Amara", "Abdelouali", "Amer", "Abdelouarete", "Ameur", "Abdenbi", "Ameziane", "Baaka", "Bachar", "Baaqa", "Baba", "Badr", "Badr", "Ezzamane", "Badr", "Eddine", "Badri", "Bahae", "Bahi", "Bahssin", "Bachir", "Bakkar", "Bakr", "Bamou", "Barouk", "Belkassem", "Benissa", "Bassam", "Bassou", "Belaid", "Belkas", "Benaissa", "Benasser", "Bendaoud", "Bennacer", "Benyaakoub", "Bichara", "Bichr", "Bikr", "Bilal", "Bouamama", "Bouamar", "Bouamrou", "Bouazza", "Bouchaib", "Bouekri", "Bouchta", "Bouhout", "Boujemaa", "Bourhim", "Bourhime", "Bousedra", "Bouselham", "Bouziane", "Brahim", "Brik", "Chaabane", "Chaddad", "Chadi", "Chadli", "Chafai", "Chafik", "Chafiq", "Chahed", "Chahid", "Chaib", "Chakib", "Chakir", "Chaouki", "Charaf", "Charaf", "Eddine", "Charki", "Chedad", "Cherqi", "Chihab", "Choaib", "Chouaib", "Choukri", "Dahane", "Dahbi", "Dah", "Mane", "Daidai", "Dalil", "Daoud", "Daoui", "Darid", "Darous", "Diab", "Diae", "Diae", "Eddine", "Didi", "Douraid", "Driss", "Eddaoui", "Elaid", "Elarabi", "Elarbi", "Elaydi", "Elbachir", "Elbouchtaoui", "Elchafii", "Elchahid", "Ebdelkahar", "Ebdelkayyaoum", "Ebdelkahar", "Elfatmi", "Elghali", "Elghaouti", "Elghazouani", "Elhabib", "Elmokhtar", "Elhachemi", "Elhassan", "Elhouari", "Elkebir", "Elkhadioui", "Elkhadir", "Elkhamar", "Elmadani", "Essghir", "Elmostafa", "Elmouloudi", "Elouafi", "Elyazi", "Ezzine", "Eloualid", "Elmahdi", "Elmahi", "Elmahjoub", "Elmakki", "Fadoul", "Fael", "Fathoune", "Fahd", "Faras", "Fahim", "Fettah", "Fikri", "Fouad", "Frahat", "Fahmi", "Farji", "Farouk", "Faik", "Farid", "Fath", "Allah", "Fath", "Elkhir", "Fail", "Faraji", "Fares", "Farhate", "Fathi", "Faissal", "Fadel", "Faiz", "Fakher", "Fakhr", "Eddine", "Faouaz", "Faouzi", "Ghafour", "Ghali", "Ghanem", "Ghanim", "Gharib", "Ghassan", "Ghazal", "Ghazi", "Ghazil", "Habib", "Hossam", "Habib", "Allah", "Hossam", "Eddine", "Habika", "Houari", "Hachem", "Houcine", "Haddaoui", "Houd", "Haddou", "Houdaifa", "Hadi", "Houmad", "Hadou", "Houmam", "Hafid", "Houmane", "Hafs", "Hoummane", "Haidar", "Hourma", "Haitam", "Houssam", "Hajaj", "Houssine", "Hajjaj", "Houssni", "Hakim", "Hsina", "Halim", "Hssina", "Hamd", "Hamda", "Hamdane", "Hamdi", "Hamid", "Hamidan", "Hammadi", "Hamiddouche", "Hammam", "Hammed", "Hamou", "Hamoud", "Hamouda", "Hamza", "Hanafi", "Hani", "Hanifa", "Harouch", "Harrou", "Hassan", "Haroun", "Hassoun", "Hatim", "Hazaz", "Hazem", "Hazim", "Hicham", "Hilmi", "Hmad", "Hmida", "Hmidane", "Hmidouch", "Horma", "Hosni", "Iad", "Ibrahim", "Ider", "Idriss", "Ihssane", "Ikbal", "Ilias", "Ilyas", "Imad", "Imad", "Eddine", "Imran", "Irchad", "Isaad", "Ishaq", "Ismail", "Issa", "Iyad", "Issam", "Jaafar", "Jabbour", "Jaber", "Jabir", "Jabour", "Jabrane", "Jad", "Jad", "Elmoula", "Jadouane", "Jalal", "Jalal", "Eddine", "Jalil", "Jaloul", "Jamae", "Jamal", "Jamal", "Eddine", "Jamea", "Jamil", "Jaouad", "Jaouhar", "Jar", "Allah", "Jarrah", "Jbilou", "Jilali", "Jnina", "Joundol", "Kabbour", "Kabir", "Kacem", "Kadem", "Kadhem", "Kadour", "Kais", "Kamal", "Kamel", "Kandouz", "Karam", "Karim", "Kassem", "Kassou", "Kebour", "Khachane", "Khair", "Eddine", "Khairi", "Khales", "Khalid", "Khalifa", "Khalil", "Khalis", "Khatib", "Kotb", "Kouider", "Labib", "Lahbib", "Lahcen", "Laite", "Laith", "Lakbir", "Lakhdar", "Larbi", "Latif", "Layachi", "Lokmane", "Lotfi", "Louay", "Loukman", "Lounes", "Lounis", "Loutfi", "Mahdi", "Maamar", "Maamoun", "Maarouf", "Maatallah", "Maati", "Mabrouk", "Machich", "Madani", "Mahboub", "Maher", "Mahfoud", "Mahjoub", "Mahjoubi", "Mahmoud", "Mahraz", "Mahrez", "Majd", "Majdoub", "Majid", "Makhlouf", "Malek", "Malih", "Mallal", "Mamdouh", "Mamoun", "Mandil", "Mansour", "Marouane", "Marzak", "Marzouk", "Masaoud", "Masrour", "Massoud", "Mazigh", "M’barek", "Mesbah", "Meziane", "M’hamed", "Mimoun", "Mnaouar", "Moad", "Moaouia", "Moataz", "Mobarek", "Mofid", "Moflih", "N", "Nabih", "Nabil", "Nacer", "Nader", "Nadim", "Nadir", "Nafie", "Nafis", "Nail", "Naim", "Najah", "Najd", "Najem", "Naji", "Najib", "Najm", "Eddine", "Namir", "Naoufal", "Nasr", "Nasr", "Eddine", "Nassef", "Nassif", "Nassih", "Nassim", "Nazih", "Nezar", "Nizar", "Nouaman", "Nouh", "Nour", "Nour", "Eddine", "Nouri", "O", "Okacha", "Okba", "Omar", "Osmane", "Otaiba", "Othmane", "Ouadie", "Ouael", "Ouafi", "Ouafik", "Ouahab", "Ouahib", "Ouahid", "Ouail", "Ouajdi", "Ouajih", "Oualid", "Oualim", "Ouassim", "Ounssi", "Oussama", "Outaiba", "R", "Rabbah", "Rabeh", "Rabie", "Rachad", "Rached", "Rachid", "Radi", "Raed", "Rafie", "Rafik", "Rahali", "Rahim", "Rahmoun", "Raif", "Ramdane", "Ramzi", "Raouad", "Raouf", "Rayan", "Razane", "Razek", "Razouk", "Reda", "Reda", "Allah", "Redad", "Redouane", "Refki", "Reyad", "Rezki", "Rhassane", "Riad", "Rouchdi", "Rostom", "S", "Saad", "Saad", "Eddine", "Saadoune", "Saber", "Sabih", "Sabri", "Sadik", "Saeb", "Safi", "Safouane", "Saghir", "Sahel", "Said", "Saif", "Saif", "Eddine", "Saif", "Elarab", "Saif", "Elislam", "Salah", "Salah", "Eddine", "Salam", "Salama", "Saleh", "Salem", "Salim", "Sallam", "Salmane", "Samad", "Sami", "Samih", "Samir", "Saoud", "Rochd", "Sarhane", "Sarie", "Seddik", "Sedki", "Selam", "Seouar", "Sobhi", "Sofiane", "Sohaib", "Soltan", "Soubhi", "Souhaib", "Souhail", "Soulaimane", "Soultane", "Sourour", "Stela", "Tachfine", "Taha", "Taher", "Taib", "Taibi", "Taj", "Eddine", "Taki", "Eddine", "Talal", "Taleb", "Talha", "Tami", "Tamime", "Taoufik", "Tarik", "Tareq", "Thami", "Tijani", "Tofail", "Touhami", "Yaakoob", "Yachou", "Yahia", "Yahya", "Yakd", "Yanis", "Yasser", "Yassine", "Yassir", "Yazid", "Younes", "Yousri", "Youssef", "Zahid", "Zahir", "Zaid", "Zakaria", "Zaki", "Zekri", "Zeriab", "Zeroual", "Zeryab", "Zidane", "Zine", "Zine", "Eddine", "Zine", "Elabidine", "Ziyad", "Zoubir", "Zouhir"
                   ];

// Last names array
const lastNames = [
"Benabdallah",
"Benali",
"Benani",
"Benhammou",
"Benjelloun",
"Benkirane",
"Benlafkih",
"Benmoussa",
"Benoit",
"Benomar",
"Bensaïd",
"Bensouda",
"Bensoudan",
"Bouabid",
"Boualam",
"Bouazza",
"Boubker",
"Bouchara",
"Bouchikhi",
"Boufadene",
"Bouhafs",
"Bouhaddou",
"Bouhali",
"Bouhdoud",
"Boujida",
"Boukili",
"Boularès",
"Boumadiane",
"Boumaza",
"Bounoua",
"Boussoufa",
"Boustila",
"Chraibi",
"Daoudi",
"El Alami",
"El Bouzidi",
"El Fassi",
"El Ghazi",
"El Guerrouj",
"El Hachimi",
"El Haddad",
"El Hamdaoui",
"El Khiyari",
"El Koubi",
"El Mernissi",
"El Omari",
"El Otmani",
"El Ourak",
"El Wafi",
"El Yazghi",
"Essakalli",
"Fassi-Fihri",
"Fettah",
"Filali",
"Ghoulam",
"Guennoun",
"Haddad",
"Hamouchene",
"Hanchi",
"Harouchi",
"Hassad",
"Hdidou",
"Himmi",
"Idrissi",
"Jabrane",
"Jazouli",
"Kabbaj",
"Kadiri",
"Kassimi",
"Kettani",
"Khallouki",
"Khattabi",
"Khiame",
"Lahlou",
"Lahlouh",
"Lakhal",
"Lamrani",
"Lazaar",
"Lemsagam",
"Maârouf",
"Madih",
"Mahjoubi",
"Majidi",
"Mansouri",
"Marrakchi",
"Mellouki",
"Merini",
"Messaoudi",
"Mimouni",
"Mokhtari",
"Moudden",
"Mouhoubi",
"Moukharik",
"Moulay",
"Naciri",
"Nafzawi",
"Najim",
"Ouazzani",
"Rachidi",
"Roudani",
"Sabir",
"Saâdane",
"Sabri",
"Sadiki",
"Sbaï",
"Sebban",
"Sekkat",
"Serraj",
"Serroukh",
"Skalli",
"Slimani",
"Tazi",
"Tazi-Rachedi",
"Tber",
"Temsamani",
"Tijani",
"Timoumi",
"Touijer",
"Yaacoubi",
"Yahyaoui",
"Yassine",
"Zeroual",
"Zerouali",
"Zerouati",
"Zerrouk",
"Zerrouki",
"Ziani",
"Zine",
"Zouak",
"Zouari",
"Zouhir",
"Zouiten",
"Zoukani",
"Zoumana",
"Zraidi",
"Zriouil",
"Agoumi",
"Akhazzane",
"Akrich",
"Amaziane",
"Amghar",
"Amine",
"Amraoui",
"Amzil",
"Asbahi",
"Asfari",
"Asli",
"Azzouzi",
"Baali",
"Badraoui",
"Baghli",
"Bahmad",
"Bahraoui",
"Bakrim",
"Bakry",
"Bali",
"Bani",
"Barakat",
"Baroudi",
"Bataoui",
"Belamine",
"Belhaj",
"Belhanda",
"Belkhayat",
"Bellal",
"Belmokhtar",
"Benabdeljelil",
"Benabdeljalil",
"Benabid",
"Benabou",
"Benahmed",
"Benali",
"Benamar",
"Benarfa",
"Benarroch",
"Benbrahim",
"Benbrahim El Andaloussi",
"Benchaaboun",
"Benchekroun",
"Benchikh",
"Benelbarhdadi",
"Benelhadj",
"Benelhadj-Mahfoud",
"Benhamida",
"Benharbit",
"Benhassine",
"Benhayoun",
"Benhima",
"Benjelloun",
"Benjilany",
"Benkirane",
"Benkiran",
"Benkiran El Andaloussi",
"Benlahsen",
"Benlahssen",
"Benlamlih",
"Benlamine",
"Benmahmoud",
"Benmakhlouf",
"Benmoussa"]

// Function to generate a random name
function generateName() {
  const firstName = firstNames[Math.floor(Math.random() * firstNames.length)];
  const lastName = lastNames[Math.floor(Math.random() * lastNames.length)];
  const fullName = `${firstName} ${lastName}`;
  return fullName;
}

// Event listener for the generate button
const generateBtn = document.querySelector("#generateBtn");
generateBtn.addEventListener("click", () => {
  const fullNameEl = document.querySelector("#fullName");
  fullNameEl.textContent = generateName();
});
